version: '3'

services:
  nginx1:
    image: nginx:latest
    volumes:
      - ./nginx1/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"

  nginx2:
    image: nginx:latest
    volumes:
      - ./nginx2/nginx.conf:/etc/nginx/nginx.conf

  nginx3:
    image: nginx:latest
    volumes:
      - ./nginx3/nginx.conf:/etc/nginx/nginx.conf

  app:
    build: ./app
    ports:
      - "8080:8080"